-- Add frequency column if table already exists from earlier migration
alter table public.delivery_zones
  add column if not exists frequency text not null default 'Daily';

-- Clear old seed data so we can insert fresh from Google Sheet
truncate public.delivery_zones;

insert into public.delivery_zones (postcode, area_name, city, state, frequency) values
-- W.P. KUALA LUMPUR
('50000','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50050','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50088','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50100','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50150','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50200','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50250','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50300','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50350','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50400','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50450','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50460','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50470','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50480','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50490','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50500','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50502','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50504','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50505','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50506','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50507','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50508','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50510','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50512','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50514','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50515','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50519','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50528','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50530','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50532','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50534','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50536','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50538','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50540','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50544','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50546','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50548','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50550','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50551','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50552','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50554','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50556','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50560','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50564','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50570','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50576','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50578','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50580','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50582','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50586','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50590','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50592','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50594','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50596','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50598','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50600','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50604','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50608','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50609','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50610','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50612','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50614','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50620','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50622','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50626','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50632','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50644','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50648','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50660','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50662','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50664','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50670','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50672','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50673','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50676','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50680','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50694','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('50988','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('51000','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('51100','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('51200','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('52000','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('52100','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('52200','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('53000','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('53100','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('53200','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('53300','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('53500','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('54000','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('54100','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('54200','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('55000','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('55100','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('55188','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('55200','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('55300','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('56000','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('56100','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('57000','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('57100','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('58000','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('58100','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('58200','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('58990','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('59000','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('59100','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('59200','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('59700','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
('60000','Kuala Lumpur','Kuala Lumpur','W.P. Kuala Lumpur','Daily'),
-- SELANGOR
('40000','Shah Alam','Shah Alam','Selangor','Daily'),
('40100','Shah Alam','Shah Alam','Selangor','Daily'),
('40150','Shah Alam','Shah Alam','Selangor','Daily'),
('40160','Shah Alam','Shah Alam','Selangor','Daily'),
('40170','Shah Alam','Shah Alam','Selangor','Daily'),
('40200','Shah Alam','Shah Alam','Selangor','Daily'),
('40300','Shah Alam','Shah Alam','Selangor','Daily'),
('40400','Shah Alam','Shah Alam','Selangor','Daily'),
('40450','Shah Alam','Shah Alam','Selangor','Daily'),
('40460','Shah Alam','Shah Alam','Selangor','Daily'),
('40470','Shah Alam','Shah Alam','Selangor','Daily'),
('40500','Shah Alam','Shah Alam','Selangor','Daily'),
('40502','Shah Alam','Shah Alam','Selangor','Daily'),
('40503','Shah Alam','Shah Alam','Selangor','Daily'),
('40505','Shah Alam','Shah Alam','Selangor','Daily'),
('40512','Shah Alam','Shah Alam','Selangor','Daily'),
('40517','Shah Alam','Shah Alam','Selangor','Daily'),
('40520','Shah Alam','Shah Alam','Selangor','Daily'),
('40550','Shah Alam','Shah Alam','Selangor','Daily'),
('40560','Shah Alam','Shah Alam','Selangor','Daily'),
('40564','Shah Alam','Shah Alam','Selangor','Daily'),
('40570','Shah Alam','Shah Alam','Selangor','Daily'),
('40572','Shah Alam','Shah Alam','Selangor','Daily'),
('40576','Shah Alam','Shah Alam','Selangor','Daily'),
('40578','Shah Alam','Shah Alam','Selangor','Daily'),
('40582','Shah Alam','Shah Alam','Selangor','Daily'),
('40590','Shah Alam','Shah Alam','Selangor','Daily'),
('40592','Shah Alam','Shah Alam','Selangor','Daily'),
('40594','Shah Alam','Shah Alam','Selangor','Daily'),
('40596','Shah Alam','Shah Alam','Selangor','Daily'),
('40604','Shah Alam','Shah Alam','Selangor','Daily'),
('40607','Shah Alam','Shah Alam','Selangor','Daily'),
('40608','Shah Alam','Shah Alam','Selangor','Daily'),
('40610','Shah Alam','Shah Alam','Selangor','Daily'),
('40612','Shah Alam','Shah Alam','Selangor','Daily'),
('40620','Shah Alam','Shah Alam','Selangor','Daily'),
('40622','Shah Alam','Shah Alam','Selangor','Daily'),
('40626','Shah Alam','Shah Alam','Selangor','Daily'),
('40632','Shah Alam','Shah Alam','Selangor','Daily'),
('40646','Shah Alam','Shah Alam','Selangor','Daily'),
('40648','Shah Alam','Shah Alam','Selangor','Daily'),
('40660','Shah Alam','Shah Alam','Selangor','Daily'),
('40664','Shah Alam','Shah Alam','Selangor','Daily'),
('40670','Shah Alam','Shah Alam','Selangor','Daily'),
('40672','Shah Alam','Shah Alam','Selangor','Daily'),
('40673','Shah Alam','Shah Alam','Selangor','Daily'),
('40674','Shah Alam','Shah Alam','Selangor','Daily'),
('40675','Shah Alam','Shah Alam','Selangor','Daily'),
('40676','Shah Alam','Shah Alam','Selangor','Daily'),
('40680','Shah Alam','Shah Alam','Selangor','Daily'),
('40690','Shah Alam','Shah Alam','Selangor','Daily'),
('41000','Klang','Klang','Selangor','Daily'),
('41050','Klang','Klang','Selangor','Daily'),
('41100','Klang','Klang','Selangor','Daily'),
('41150','Klang','Klang','Selangor','Daily'),
('41200','Klang','Klang','Selangor','Daily'),
('41250','Klang','Klang','Selangor','Daily'),
('41300','Klang','Klang','Selangor','Daily'),
('41400','Klang','Klang','Selangor','Daily'),
('41506','Klang','Klang','Selangor','Daily'),
('41560','Klang','Klang','Selangor','Daily'),
('41586','Klang','Klang','Selangor','Daily'),
('41672','Klang','Klang','Selangor','Daily'),
('41700','Klang','Klang','Selangor','Daily'),
('42000','Pelabuhan Klang','Klang','Selangor','Daily'),
('42100','Klang','Klang','Selangor','Daily'),
('42200','Kapar','Klang','Selangor','Daily'),
('42300','Bandar Puncak Alam','Klang','Selangor','Daily'),
('42425','Shah Alam','Shah Alam','Selangor','Daily'),
('42450','Shah Alam','Shah Alam','Selangor','Daily'),
('42500','Telok Panglima Garang','Klang','Selangor','Daily'),
('42600','Jenjarom','Klang','Selangor','Daily'),
('42610','Jenjarom','Klang','Selangor','Daily'),
('42700','Banting','Kuala Langat','Selangor','Mon, Wed, Fri'),
('42800','Tanjong Sepat','Kuala Langat','Selangor','Mon, Wed, Fri'),
('42920','Pulau Indah','Klang','Selangor','Tue, Thu, Sat'),
('43000','Kajang','Kajang','Selangor','Daily'),
('43100','Hulu Langat','Hulu Langat','Selangor','Tue, Thu, Sat'),
('43200','Cheras','Kajang','Selangor','Daily'),
('43207','Cheras','Kajang','Selangor','Daily'),
('43300','Seri Kembangan','Sepang','Selangor','Daily'),
('43400','Serdang','Sepang','Selangor','Daily'),
('43500','Semenyih','Kajang','Selangor','Daily'),
('43558','Kajang','Kajang','Selangor','Daily'),
('43600','Bandar Baru Bangi','Kajang','Selangor','Daily'),
('43650','Bandar Baru Bangi','Kajang','Selangor','Daily'),
('43659','Bandar Baru Bangi','Kajang','Selangor','Daily'),
('43700','Beranang','Kajang','Selangor','Daily'),
('43800','Dengkil','Sepang','Selangor','Mon, Wed, Fri'),
('43900','Sepang','Sepang','Selangor','Mon, Wed, Fri'),
('43950','Sungai Pelek','Sepang','Selangor','Mon, Wed, Fri'),
('44000','Kuala Kubu Baru','Hulu Selangor','Selangor','Mon, Wed, Fri'),
('44100','Kerling','Hulu Selangor','Selangor','Mon, Wed, Fri'),
('44200','Rasa','Hulu Selangor','Selangor','Mon, Wed, Fri'),
('44300','Batang Kali','Hulu Selangor','Selangor','Mon, Wed, Fri'),
('45000','Kuala Selangor','Kuala Selangor','Selangor','Tue, Thu, Sat'),
('45100','Sungai Ayer Tawar','Kuala Selangor','Selangor','Tue, Thu, Sat'),
('45200','Sabak Bernam','Sabak Bernam','Selangor','Tue, Thu, Sat'),
('45300','Sungai Besar','Sabak Bernam','Selangor','Tue, Thu, Sat'),
('45400','Sekinchan','Sabak Bernam','Selangor','Tue, Thu, Sat'),
('45500','Tanjong Karang','Kuala Selangor','Selangor','Tue, Thu, Sat'),
('45600','Bestari Jaya','Kuala Selangor','Selangor','Tue, Thu, Sat'),
('45607','Bestari Jaya','Kuala Selangor','Selangor','Tue, Thu, Sat'),
('45609','Bestari Jaya','Kuala Selangor','Selangor','Tue, Thu, Sat'),
('45620','Bestari Jaya','Kuala Selangor','Selangor','Tue, Thu, Sat'),
('45700','Bukit Rotan','Kuala Selangor','Selangor','Tue, Thu, Sat'),
('45800','Jeram','Kuala Selangor','Selangor','Tue, Thu, Sat'),
('46000','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46050','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46100','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46150','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46200','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46300','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46350','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46400','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46506','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46547','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46549','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46551','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46564','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46582','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46598','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46662','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46667','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46668','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46672','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46675','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46700','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46710','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46720','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46730','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46750','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46770','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46783','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('46978','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('47000','Sungai Buloh','Petaling','Selangor','Daily'),
('47100','Puchong','Puchong','Selangor','Daily'),
('47110','Puchong','Puchong','Selangor','Daily'),
('47120','Puchong','Puchong','Selangor','Daily'),
('47130','Puchong','Puchong','Selangor','Daily'),
('47140','Puchong','Puchong','Selangor','Daily'),
('47150','Puchong','Puchong','Selangor','Daily'),
('47160','Puchong','Puchong','Selangor','Daily'),
('47170','Puchong','Puchong','Selangor','Daily'),
('47180','Puchong','Puchong','Selangor','Daily'),
('47190','Puchong','Puchong','Selangor','Daily'),
('47200','Subang Jaya','Subang Jaya','Selangor','Daily'),
('47300','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('47301','Ara Damansara','Petaling Jaya','Selangor','Daily'),
('47307','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('47308','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('47400','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('47410','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('47500','Subang Jaya','Subang Jaya','Selangor','Daily'),
('47509','Subang Jaya','Subang Jaya','Selangor','Daily'),
('47600','Subang Jaya','Subang Jaya','Selangor','Daily'),
('47610','Subang Jaya','Subang Jaya','Selangor','Daily'),
('47620','Subang Jaya','Subang Jaya','Selangor','Daily'),
('47630','Subang Jaya','Subang Jaya','Selangor','Daily'),
('47640','Subang Jaya','Subang Jaya','Selangor','Daily'),
('47650','Subang Jaya','Subang Jaya','Selangor','Daily'),
('47800','Petaling Jaya','Petaling Jaya','Selangor','Daily'),
('47810','Subang Perdana','Subang Jaya','Selangor','Daily'),
('47820','Damansara Damai','Petaling Jaya','Selangor','Daily'),
('47830','Damansara','Petaling Jaya','Selangor','Daily'),
('48000','Rawang','Gombak','Selangor','Mon, Wed, Fri'),
('48010','Rawang','Gombak','Selangor','Mon, Wed, Fri'),
('48020','Rawang','Gombak','Selangor','Mon, Wed, Fri'),
('48050','Rawang','Gombak','Selangor','Mon, Wed, Fri'),
('48100','Batu Arang','Gombak','Selangor','Tue, Thu, Sat'),
('48200','Serendah','Hulu Selangor','Selangor','Mon, Wed, Fri'),
('48300','Rawang','Gombak','Selangor','Mon, Wed, Fri'),
('63000','Cyberjaya','Cyberjaya','Selangor','Daily'),
('63100','Cyberjaya','Cyberjaya','Selangor','Daily'),
('63200','Sepang','Sepang','Selangor','Daily'),
('63300','Sepang','Sepang','Selangor','Daily'),
('68000','Ampang','Gombak','Selangor','Daily'),
('68100','Batu Caves','Gombak','Selangor','Daily'),
-- W.P. PUTRAJAYA
('62000','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62007','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62050','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62100','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62150','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62200','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62250','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62300','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62350','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62502','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62504','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62505','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62506','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62510','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62512','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62514','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62516','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62517','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62518','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62519','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62520','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62522','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62524','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62526','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62527','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62530','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62532','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62536','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62540','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62542','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62546','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62550','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62551','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62564','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62570','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62574','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62576','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62582','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62584','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62590','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62592','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62594','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62596','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62600','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62602','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62604','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62605','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62606','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62607','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62612','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62616','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62618','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62620','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62622','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62624','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62628','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62630','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62632','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62640','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62644','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62648','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62662','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62670','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62674','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62676','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62686','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62690','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62692','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
('62988','Putrajaya','Putrajaya','W.P. Putrajaya','Daily'),
-- PERLIS
('01000','Kangar','Kangar','Perlis','Tue, Thu, Sat'),
('01007','Kangar','Kangar','Perlis','Daily'),
('01009','Kangar','Kangar','Perlis','Daily'),
('01500','Kangar','Kangar','Perlis','Daily'),
('01502','Kangar','Kangar','Perlis','Daily'),
('01503','Kangar','Kangar','Perlis','Daily'),
('01504','Kangar','Kangar','Perlis','Daily'),
('01505','Kangar','Kangar','Perlis','Daily'),
('01506','Kangar','Kangar','Perlis','Daily'),
('01508','Kangar','Kangar','Perlis','Daily'),
('01512','Kangar','Kangar','Perlis','Daily'),
('01514','Kangar','Kangar','Perlis','Daily'),
('01516','Kangar','Kangar','Perlis','Daily'),
('01517','Kangar','Kangar','Perlis','Daily'),
('01518','Kangar','Kangar','Perlis','Daily'),
('01524','Kangar','Kangar','Perlis','Daily'),
('01529','Kangar','Kangar','Perlis','Daily'),
('01532','Kangar','Kangar','Perlis','Daily'),
('01538','Kangar','Kangar','Perlis','Daily'),
('01540','Kangar','Kangar','Perlis','Daily'),
('01542','Kangar','Kangar','Perlis','Daily'),
('01546','Kangar','Kangar','Perlis','Daily'),
('01550','Kangar','Kangar','Perlis','Daily'),
('01551','Kangar','Kangar','Perlis','Daily'),
('01556','Kangar','Kangar','Perlis','Daily'),
('01560','Kangar','Kangar','Perlis','Daily'),
('01564','Kangar','Kangar','Perlis','Daily'),
('01570','Kangar','Kangar','Perlis','Daily'),
('01572','Kangar','Kangar','Perlis','Daily'),
('01576','Kangar','Kangar','Perlis','Daily'),
('01578','Kangar','Kangar','Perlis','Daily'),
('01582','Kangar','Kangar','Perlis','Daily'),
('01586','Kangar','Kangar','Perlis','Daily'),
('01590','Kangar','Kangar','Perlis','Daily'),
('01592','Kangar','Kangar','Perlis','Daily'),
('01594','Kangar','Kangar','Perlis','Daily'),
('01596','Kangar','Kangar','Perlis','Daily'),
('01598','Kangar','Kangar','Perlis','Daily'),
('01600','Kangar','Kangar','Perlis','Daily'),
('01604','Kangar','Kangar','Perlis','Daily'),
('01606','Kangar','Kangar','Perlis','Daily'),
('01608','Kangar','Kangar','Perlis','Daily'),
('01609','Kangar','Kangar','Perlis','Daily'),
('01610','Kangar','Kangar','Perlis','Daily'),
('01612','Kangar','Kangar','Perlis','Daily'),
('01614','Kangar','Kangar','Perlis','Daily'),
('01620','Kangar','Kangar','Perlis','Daily'),
('01622','Kangar','Kangar','Perlis','Daily'),
('01626','Kangar','Kangar','Perlis','Daily'),
('01628','Kangar','Kangar','Perlis','Daily'),
('01630','Kangar','Kangar','Perlis','Daily'),
('01632','Kangar','Kangar','Perlis','Daily'),
('01634','Kangar','Kangar','Perlis','Daily'),
('01644','Kangar','Kangar','Perlis','Daily'),
('01646','Kangar','Kangar','Perlis','Daily'),
('01648','Kangar','Kangar','Perlis','Daily'),
('01660','Kangar','Kangar','Perlis','Daily'),
('01664','Kangar','Kangar','Perlis','Daily'),
('01670','Kangar','Kangar','Perlis','Daily'),
('01672','Kangar','Kangar','Perlis','Daily'),
('01673','Kangar','Kangar','Perlis','Daily'),
('01674','Kangar','Kangar','Perlis','Daily'),
('01676','Kangar','Kangar','Perlis','Daily'),
('01680','Kangar','Kangar','Perlis','Daily'),
('01694','Kangar','Kangar','Perlis','Daily'),
('02000','Kuala Perlis','Kuala Perlis','Perlis','Daily'),
('02100','Padang Besar','Padang Besar','Perlis','Tue, Thu, Sat'),
('02200','Kaki Bukit','Kaki Bukit','Perlis','Tue, Thu, Sat'),
('02400','Kangar','Kangar','Perlis','Tue, Thu, Sat'),
('02450','Kangar','Kangar','Perlis','Tue, Thu, Sat'),
('02500','Kangar','Kangar','Perlis','Tue, Thu, Sat'),
('02600','Arau','Arau','Perlis','Tue, Thu, Sat'),
('02607','Arau','Arau','Perlis','Daily'),
('02609','Arau','Arau','Perlis','Daily'),
('02700','Simpang Ampat','Simpang Ampat','Perlis','Daily'),
('02707','Simpang Ampat','Simpang Ampat','Perlis','Daily'),
('02709','Simpang Ampat','Simpang Ampat','Perlis','Daily'),
('02800','Simpang Ampat','Simpang Ampat','Perlis','Daily'),
-- KEDAH
('05000','Alor Setar','Alor Setar','Kedah','Daily'),
('05050','Alor Setar','Alor Setar','Kedah','Daily'),
('05100','Alor Setar','Alor Setar','Kedah','Daily'),
('05150','Alor Setar','Alor Setar','Kedah','Daily'),
('05200','Alor Setar','Alor Setar','Kedah','Daily'),
('05250','Alor Setar','Alor Setar','Kedah','Daily'),
('05300','Alor Setar','Alor Setar','Kedah','Daily'),
('05350','Alor Setar','Alor Setar','Kedah','Daily'),
('05400','Alor Setar','Alor Setar','Kedah','Daily'),
('05460','Alor Setar','Alor Setar','Kedah','Daily'),
('05500','Alor Setar','Alor Setar','Kedah','Daily'),
('05502','Alor Setar','Alor Setar','Kedah','Daily'),
('05550','Alor Setar','Alor Setar','Kedah','Daily'),
('05600','Alor Setar','Alor Setar','Kedah','Daily'),
('05700','Alor Setar','Alor Setar','Kedah','Daily'),
('05990','Alor Setar','Alor Setar','Kedah','Daily'),
('06000','Jitra','Jitra','Kedah','Mon, Wed, Fri'),
('06007','Jitra','Jitra','Kedah','Mon, Wed, Fri'),
('06009','Jitra','Jitra','Kedah','Mon, Wed, Fri'),
('06050','Bukit Kayu Hitam','Bukit Kayu Hitam','Kedah','Mon, Wed, Fri'),
('06100','Kodiang','Kodiang','Kedah','Mon, Wed, Fri'),
('06200','Kepala Batas','Kepala Batas','Kedah','Mon, Wed, Fri'),
('06250','Alor Setar','Alor Setar','Kedah','Daily'),
('06300','Kuala Nerang','Kuala Nerang','Kedah','Mon, Wed, Fri'),
('06350','Pokok Sena','Pokok Sena','Kedah','Mon, Wed, Fri'),
('06400','Pokok Sena','Pokok Sena','Kedah','Mon, Wed, Fri'),
('06500','Langgar','Langgar','Kedah','Daily'),
('06600','Kuala Kedah','Kuala Kedah','Kedah','Daily'),
('06650','Simpang Empat','Simpang Empat','Kedah','Daily'),
('06660','Simpang Empat','Simpang Empat','Kedah','Daily'),
('06700','Pendang','Pendang','Kedah','Mon, Wed, Fri'),
('06800','Kota Sarang Semut','Kota Sarang Semut','Kedah','Daily'),
('06900','Yan','Yan','Kedah','Daily'),
('06910','Yan','Yan','Kedah','Daily'),
('08000','Sungai Petani','Sungai Petani','Kedah','Daily'),
('08007','Sungai Petani','Sungai Petani','Kedah','Daily'),
('08009','Sungai Petani','Sungai Petani','Kedah','Daily'),
('08010','Sungai Petani','Sungai Petani','Kedah','Daily'),
('08100','Bedong','Bedong','Kedah','Daily'),
('08107','Bedong','Bedong','Kedah','Daily'),
('08110','Bedong','Bedong','Kedah','Daily'),
('08200','Sik','Sik','Kedah','Tue, Thu, Sat'),
('08210','Sik','Sik','Kedah','Tue, Thu, Sat'),
('08300','Gurun','Gurun','Kedah','Daily'),
('08307','Gurun','Gurun','Kedah','Daily'),
('08320','Jeniang','Jeniang','Kedah','Tue, Thu, Sat'),
('08400','Merbok','Merbok','Kedah','Daily'),
('08407','Merbok','Merbok','Kedah','Daily'),
('08409','Merbok','Merbok','Kedah','Daily'),
('08500','Kota Kuala Muda','Kota Kuala Muda','Kedah','Daily'),
('08507','Kota Kuala Muda','Kota Kuala Muda','Kedah','Daily'),
('08509','Kota Kuala Muda','Kota Kuala Muda','Kedah','Daily'),
('08600','Sungai Petani','Sungai Petani','Kedah','Daily'),
('08700','Jeniang','Jeniang','Kedah','Tue, Thu, Sat'),
('08800','Gurun','Gurun','Kedah','Daily'),
('09000','Kulim','Kulim','Kedah','Tue, Thu, Sat'),
('09007','Kulim','Kulim','Kedah','Tue, Thu, Sat'),
('09009','Kulim','Kulim','Kedah','Tue, Thu, Sat'),
('09010','Kulim','Kulim','Kedah','Tue, Thu, Sat'),
('09020','Kulim','Kulim','Kedah','Tue, Thu, Sat'),
('09100','Baling','Baling','Kedah','Tue, Thu, Sat'),
('09109','Baling','Baling','Kedah','Tue, Thu, Sat'),
('09110','Kuala Pegang','Baling','Kedah','Tue, Thu, Sat'),
('09120','Baling','Baling','Kedah','Tue, Thu, Sat'),
('09130','Baling','Baling','Kedah','Tue, Thu, Sat'),
('09200','Kupang','Kupang','Kedah','Tue, Thu, Sat'),
('09300','Kuala Ketil','Kuala Ketil','Kedah','Tue, Thu, Sat'),
('09309','Kuala Ketil','Kuala Ketil','Kedah','Tue, Thu, Sat'),
('09310','Kuala Ketil','Kuala Ketil','Kedah','Tue, Thu, Sat'),
('09400','Padang Serai','Padang Serai','Kedah','Tue, Thu, Sat'),
('09409','Padang Serai','Padang Serai','Kedah','Tue, Thu, Sat'),
('09410','Padang Serai','Padang Serai','Kedah','Tue, Thu, Sat'),
('09500','Karangan','Karangan','Kedah','Tue, Thu, Sat'),
('09600','Lunas','Lunas','Kedah','Tue, Thu, Sat'),
('09700','Karangan','Karangan','Kedah','Tue, Thu, Sat'),
('09709','Karangan','Karangan','Kedah','Tue, Thu, Sat'),
('09800','Serdang','Serdang','Kedah','Tue, Thu, Sat'),
('09809','Serdang','Serdang','Kedah','Tue, Thu, Sat'),
('09810','Serdang','Serdang','Kedah','Tue, Thu, Sat'),
-- PULAU PINANG
('10000','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10050','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10100','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10150','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10200','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10250','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10300','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10350','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10400','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10450','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10460','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10470','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10500','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10550','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10600','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10700','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10800','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10910','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10920','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('10990','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('11000','Balik Pulau','Balik Pulau','Pulau Pinang','Daily'),
('11010','Balik Pulau','Balik Pulau','Pulau Pinang','Daily'),
('11020','Balik Pulau','Balik Pulau','Pulau Pinang','Daily'),
('11050','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('11060','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('11100','Batu Ferringhi','Batu Ferringhi','Pulau Pinang','Daily'),
('11200','Tanjong Bungah','Tanjong Bungah','Pulau Pinang','Daily'),
('11300','Penang Hill','Penang Hill','Pulau Pinang','Daily'),
('11400','Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('11500','Ayer Itam','Ayer Itam','Pulau Pinang','Daily'),
('11600','Jelutong','Jelutong','Pulau Pinang','Daily'),
('11700','Gelugor','Gelugor','Pulau Pinang','Daily'),
('11800','USM Pulau Pinang','Pulau Pinang','Pulau Pinang','Daily'),
('11900','Bayan Lepas','Bayan Lepas','Pulau Pinang','Daily'),
('11910','Bayan Lepas','Bayan Lepas','Pulau Pinang','Daily'),
('11920','Bayan Lepas','Bayan Lepas','Pulau Pinang','Daily'),
('11950','Bayan Lepas','Bayan Lepas','Pulau Pinang','Daily'),
('11960','Batu Maung','Batu Maung','Pulau Pinang','Daily'),
('12000','Butterworth','Butterworth','Pulau Pinang','Daily'),
('12100','Butterworth','Butterworth','Pulau Pinang','Daily'),
('12200','Butterworth','Butterworth','Pulau Pinang','Daily'),
('12300','Butterworth','Butterworth','Pulau Pinang','Daily'),
('12700','Butterworth','Butterworth','Pulau Pinang','Daily'),
('12990','Butterworth','Butterworth','Pulau Pinang','Daily'),
('13000','Butterworth','Butterworth','Pulau Pinang','Daily'),
('13009','Butterworth','Butterworth','Pulau Pinang','Daily'),
('13020','Butterworth','Butterworth','Pulau Pinang','Daily'),
('13050','Butterworth','Butterworth','Pulau Pinang','Daily'),
('13100','Penaga','Penaga','Pulau Pinang','Daily'),
('13110','Penaga','Penaga','Pulau Pinang','Daily'),
('13200','Kepala Batas','Kepala Batas','Pulau Pinang','Daily'),
('13210','Kepala Batas','Kepala Batas','Pulau Pinang','Daily'),
('13220','Kepala Batas','Kepala Batas','Pulau Pinang','Daily'),
('13300','Tasek Gelugor','Tasek Gelugor','Pulau Pinang','Daily'),
('13310','Tasek Gelugor','Tasek Gelugor','Pulau Pinang','Daily'),
('13400','Butterworth','Butterworth','Pulau Pinang','Daily'),
('13500','Permatang Pauh','Permatang Pauh','Pulau Pinang','Daily'),
('13600','Perai','Perai','Pulau Pinang','Daily'),
('13700','Perai','Perai','Pulau Pinang','Daily'),
('13800','Butterworth','Butterworth','Pulau Pinang','Daily'),
('14000','Bukit Mertajam','Bukit Mertajam','Pulau Pinang','Daily'),
('14007','Bukit Mertajam','Bukit Mertajam','Pulau Pinang','Daily'),
('14009','Bukit Mertajam','Bukit Mertajam','Pulau Pinang','Daily'),
('14020','Bukit Mertajam','Bukit Mertajam','Pulau Pinang','Daily'),
('14100','Simpang Ampat','Simpang Ampat','Pulau Pinang','Daily'),
('14110','Simpang Ampat','Simpang Ampat','Pulau Pinang','Daily'),
('14120','Simpang Ampat','Simpang Ampat','Pulau Pinang','Daily'),
('14200','Sungai Jawi','Sungai Jawi','Pulau Pinang','Daily'),
('14300','Nibong Tebal','Nibong Tebal','Pulau Pinang','Daily'),
('14310','Nibong Tebal','Nibong Tebal','Pulau Pinang','Daily'),
('14320','Nibong Tebal','Nibong Tebal','Pulau Pinang','Daily'),
('14400','Kubang Semang','Kubang Semang','Pulau Pinang','Daily'),
-- PERAK
('30000','Ipoh','Ipoh','Perak','Daily'),
('30010','Ipoh','Ipoh','Perak','Daily'),
('30020','Ipoh','Ipoh','Perak','Daily'),
('30100','Ipoh','Ipoh','Perak','Daily'),
('30200','Ipoh','Ipoh','Perak','Daily'),
('30250','Ipoh','Ipoh','Perak','Daily'),
('30300','Ipoh','Ipoh','Perak','Daily'),
('30350','Ipoh','Ipoh','Perak','Daily'),
('30450','Ipoh','Ipoh','Perak','Daily'),
('30502','Ipoh','Ipoh','Perak','Daily'),
('30550','Ipoh','Ipoh','Perak','Daily'),
('30600','Ipoh','Ipoh','Perak','Daily'),
('30700','Ipoh','Ipoh','Perak','Daily'),
('30800','Ipoh','Ipoh','Perak','Daily'),
('30900','Ipoh','Ipoh','Perak','Daily'),
('30990','Ipoh','Ipoh','Perak','Daily'),
('31000','Batu Gajah','Batu Gajah','Perak','Tue, Thu, Sat'),
('31007','Batu Gajah','Batu Gajah','Perak','Tue, Thu, Sat'),
('31009','Batu Gajah','Batu Gajah','Perak','Tue, Thu, Sat'),
('31050','Sungai Siput','Sungai Siput','Perak','Tue, Thu, Sat'),
('31100','Sungai Siput','Sungai Siput','Perak','Tue, Thu, Sat'),
('31150','Ulu Kinta','Ulu Kinta','Perak','Daily'),
('31200','Chemor','Chemor','Perak','Daily'),
('31250','Tanjong Rambutan','Tanjong Rambutan','Perak','Daily'),
('31300','Kampung Kepayang','Kampung Kepayang','Perak','Daily'),
('31400','Ipoh','Ipoh','Perak','Daily'),
('31407','Ipoh','Ipoh','Perak','Daily'),
('31409','Ipoh','Ipoh','Perak','Daily'),
('31500','Ipoh','Ipoh','Perak','Daily'),
('31550','Pusing','Pusing','Perak','Daily'),
('31560','Pusing','Pusing','Perak','Daily'),
('31600','Gopeng','Gopeng','Perak','Daily'),
('31610','Gopeng','Gopeng','Perak','Daily'),
('31700','Malim Nawar','Malim Nawar','Perak','Mon, Wed, Fri'),
('31750','Tronoh','Tronoh','Perak','Tue, Thu, Sat'),
('31800','Tanjong Tualang','Tanjong Tualang','Perak','Tue, Thu, Sat'),
('31900','Kampar','Kampar','Perak','Mon, Wed, Fri'),
('31907','Kampar','Kampar','Perak','Mon, Wed, Fri'),
('31909','Kampar','Kampar','Perak','Mon, Wed, Fri'),
('31910','Kampar','Kampar','Perak','Mon, Wed, Fri'),
('31950','Kampar','Kampar','Perak','Mon, Wed, Fri'),
('32000','Sitiawan','Sitiawan','Perak','Daily'),
('32020','Sitiawan','Sitiawan','Perak','Daily'),
('32040','Seri Manjong','Seri Manjong','Perak','Daily'),
('32100','Lumut','Lumut','Perak','Daily'),
('32200','Lumut','Lumut','Perak','Daily'),
('32400','Ayer Tawar','Ayer Tawar','Perak','Tue, Thu, Sat'),
('32407','Ayer Tawar','Ayer Tawar','Perak','Tue, Thu, Sat'),
('32500','Changkat Keruing','Changkat Keruing','Perak','Tue, Thu, Sat'),
('32600','Bota','Bota','Perak','Tue, Thu, Sat'),
('32700','Bruas','Bruas','Perak','Tue, Thu, Sat'),
('32800','Parit','Parit','Perak','Tue, Thu, Sat'),
('32900','Lambor Kanan','Lambor Kanan','Perak','Tue, Thu, Sat'),
('33000','Kuala Kangsar','Kuala Kangsar','Perak','Tue, Thu, Sat'),
('33007','Kuala Kangsar','Kuala Kangsar','Perak','Tue, Thu, Sat'),
('33009','Kuala Kangsar','Kuala Kangsar','Perak','Tue, Thu, Sat'),
('33020','Kuala Kangsar','Kuala Kangsar','Perak','Tue, Thu, Sat'),
('33500','Sauk','Sauk','Perak','Tue, Thu, Sat'),
('33600','Enggor','Enggor','Perak','Tue, Thu, Sat'),
('33700','Padang Rengas','Padang Rengas','Perak','Tue, Thu, Sat'),
('33800','Manong','Manong','Perak','Tue, Thu, Sat'),
('34000','Taiping','Taiping','Perak','Daily'),
('34007','Taiping','Taiping','Perak','Daily'),
('34008','Taiping','Taiping','Perak','Daily'),
('34009','Taiping','Taiping','Perak','Daily'),
('34010','Taiping','Taiping','Perak','Daily'),
('34100','Selama','Selama','Perak','Mon, Wed, Fri'),
('34200','Parit Buntar','Parit Buntar','Perak','Mon, Wed, Fri'),
('34300','Bagan Serai','Bagan Serai','Perak','Mon, Wed, Fri'),
('34307','Bagan Serai','Bagan Serai','Perak','Mon, Wed, Fri'),
('34350','Kuala Kurau','Kuala Kurau','Perak','Mon, Wed, Fri'),
('34400','Semanggol','Semanggol','Perak','Mon, Wed, Fri'),
('34500','Batu Kurau','Batu Kurau','Perak','Tue, Thu, Sat'),
('34600','Kamunting','Kamunting','Perak','Daily'),
('34607','Kamunting','Kamunting','Perak','Daily'),
('34650','Kuala Sepetang','Kuala Sepetang','Perak','Daily'),
('34700','Simpang','Simpang','Perak','Daily'),
('34750','Matang','Matang','Perak','Daily'),
('34800','Trong','Trong','Perak','Daily'),
('34850','Changkat Jering','Changkat Jering','Perak','Daily'),
('34900','Pantai Remis','Pantai Remis','Perak','Tue, Thu, Sat'),
('35000','Tapah','Tapah','Perak','Mon, Wed, Fri'),
('35007','Tapah','Tapah','Perak','Mon, Wed, Fri'),
('35009','Tapah','Tapah','Perak','Mon, Wed, Fri'),
('35300','Chenderiang','Chenderiang','Perak','Mon, Wed, Fri'),
('35350','Temoh','Temoh','Perak','Mon, Wed, Fri'),
('35400','Tapah Road','Tapah','Perak','Mon, Wed, Fri'),
('35500','Bidor','Bidor','Perak','Mon, Wed, Fri'),
('35507','Bidor','Bidor','Perak','Mon, Wed, Fri'),
('36000','Teluk Intan','Teluk Intan','Perak','Mon, Wed, Fri'),
('36007','Teluk Intan','Teluk Intan','Perak','Mon, Wed, Fri'),
('36009','Teluk Intan','Teluk Intan','Perak','Mon, Wed, Fri'),
('36020','Teluk Intan','Teluk Intan','Perak','Mon, Wed, Fri'),
('36030','Teluk Intan','Teluk Intan','Perak','Mon, Wed, Fri'),
('36400','Hutan Melintang','Hutan Melintang','Perak','Mon, Wed, Fri'),
('36600','Chenderong Balai','Chenderong Balai','Perak','Mon, Wed, Fri'),
('36700','Langkap','Langkap','Perak','Mon, Wed, Fri'),
('36750','Chikus','Chikus','Perak','Mon, Wed, Fri'),
-- KELANTAN
('15000','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15050','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15100','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15150','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15200','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15300','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15350','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15400','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15500','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15502','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15550','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15600','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15660','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15670','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15680','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15710','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15720','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15730','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15740','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15988','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('15990','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('16010','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('16020','Bachok','Bachok','Kelantan','Daily'),
('16030','Bachok','Bachok','Kelantan','Daily'),
('16040','Wakaf Bharu','Wakaf Bharu','Kelantan','Daily'),
('16050','Bachok','Bachok','Kelantan','Daily'),
('16060','Bachok','Bachok','Kelantan','Daily'),
('16070','Bachok','Bachok','Kelantan','Daily'),
('16080','Tumpat','Tumpat','Kelantan','Daily'),
('16090','Bachok','Bachok','Kelantan','Daily'),
('16100','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('16150','Kota Bharu','Kota Bharu','Kelantan','Daily'),
('16200','Tumpat','Tumpat','Kelantan','Daily'),
('16210','Tumpat','Tumpat','Kelantan','Daily'),
('16250','Wakaf Bharu','Wakaf Bharu','Kelantan','Daily'),
('16300','Bachok','Bachok','Kelantan','Daily'),
('16309','Bachok','Bachok','Kelantan','Daily'),
('16310','Bachok','Bachok','Kelantan','Daily'),
('16320','Bachok','Bachok','Kelantan','Daily'),
('16400','Melor','Melor','Kelantan','Daily'),
('16450','Ketereh','Ketereh','Kelantan','Daily'),
('16500','Kem Desa Pahlawan','Kem Desa Pahlawan','Kelantan','Daily'),
('16600','Pulai Chondong','Pulai Chondong','Kelantan','Daily'),
('16700','Cherang Ruku','Cherang Ruku','Kelantan','Daily'),
('16800','Pasir Puteh','Pasir Puteh','Kelantan','Daily'),
('16810','Selising','Selising','Kelantan','Daily'),
('17000','Pasir Mas','Pasir Mas','Kelantan','Daily'),
('17007','Pasir Mas','Pasir Mas','Kelantan','Daily'),
('17009','Pasir Mas','Pasir Mas','Kelantan','Daily'),
('17010','Pasir Mas','Pasir Mas','Kelantan','Daily'),
('17020','Pasir Mas','Pasir Mas','Kelantan','Daily'),
('17030','Pasir Mas','Pasir Mas','Kelantan','Daily'),
('17040','Pasir Mas','Pasir Mas','Kelantan','Daily'),
('17050','Pasir Mas','Pasir Mas','Kelantan','Daily'),
('17060','Pasir Mas','Pasir Mas','Kelantan','Daily'),
('17070','Pasir Mas','Pasir Mas','Kelantan','Daily'),
('17200','Rantau Panjang','Rantau Panjang','Kelantan','Daily'),
('17207','Rantau Panjang','Rantau Panjang','Kelantan','Daily'),
('17500','Tanah Merah','Tanah Merah','Kelantan','Daily'),
('17507','Tanah Merah','Tanah Merah','Kelantan','Daily'),
('17509','Tanah Merah','Tanah Merah','Kelantan','Daily'),
('17510','Tanah Merah','Tanah Merah','Kelantan','Daily'),
('17600','Jeli','Jeli','Kelantan','Tue, Thu, Sun'),
('17609','Jeli','Jeli','Kelantan','Tue, Thu, Sun'),
('17700','Ayer Lanas','Ayer Lanas','Kelantan','Tue, Thu, Sun'),
('18500','Machang','Machang','Kelantan','Daily'),
('18509','Machang','Machang','Kelantan','Daily'),
-- TERENGGANU
('20000','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('20050','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('20100','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('20200','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('20300','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('20400','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('20500','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('20600','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('20700','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('20900','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('20990','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('21000','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('21009','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('21010','Kuala Terengganu','Kuala Terengganu','Terengganu','Tue, Thu, Sat'),
('21020','Kuala Terengganu','Kuala Terengganu','Terengganu','Tue, Thu, Sat'),
('21030','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('21040','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('21060','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('21070','Kuala Terengganu','Kuala Terengganu','Terengganu','Mon, Wed, Fri'),
('21080','Kuala Terengganu','Kuala Terengganu','Terengganu','Mon, Wed, Fri'),
('21090','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('21100','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('21109','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('21200','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('21209','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('21210','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('21220','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('21300','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('21309','Kuala Terengganu','Kuala Terengganu','Terengganu','Daily'),
('21400','Bukit Payong','Bukit Payong','Terengganu','Daily'),
('21450','Chalok','Chalok','Terengganu','Tue, Thu, Sat'),
('21500','Sungai Tong','Sungai Tong','Terengganu','Tue, Thu, Sat'),
('21600','Marang','Marang','Terengganu','Mon, Wed, Fri'),
('21610','Marang','Marang','Terengganu','Mon, Wed, Fri'),
('21700','Kuala Berang','Kuala Berang','Terengganu','Daily'),
('21800','Ajil','Ajil','Terengganu','Daily'),
('21810','Ajil','Ajil','Terengganu','Daily'),
('21820','Ajil','Ajil','Terengganu','Daily'),
('22000','Jerteh','Jerteh','Terengganu','Tue, Thu, Sat'),
('22010','Jerteh','Jerteh','Terengganu','Tue, Thu, Sat'),
('22020','Jerteh','Jerteh','Terengganu','Tue, Thu, Sat'),
('22030','Jerteh','Jerteh','Terengganu','Tue, Thu, Sat'),
('22040','Jerteh','Jerteh','Terengganu','Tue, Thu, Sat'),
('22100','Permaisuri','Permaisuri','Terengganu','Tue, Thu, Sat'),
('22107','Permaisuri','Permaisuri','Terengganu','Tue, Thu, Sat'),
('22110','Permaisuri','Permaisuri','Terengganu','Tue, Thu, Sat'),
('22120','Permaisuri','Permaisuri','Terengganu','Tue, Thu, Sat'),
('22200','Kampung Raja','Kampung Raja','Terengganu','Tue, Thu, Sat'),
('22300','Kuala Besut','Kuala Besut','Terengganu','Tue, Thu, Sat'),
('22307','Kuala Besut','Kuala Besut','Terengganu','Tue, Thu, Sat'),
('22309','Kuala Besut','Kuala Besut','Terengganu','Tue, Thu, Sat'),
-- PAHANG
('25000','Kuantan','Kuantan','Pahang','Daily'),
('25050','Kuantan','Kuantan','Pahang','Daily'),
('25100','Kuantan','Kuantan','Pahang','Daily'),
('25150','Kuantan','Kuantan','Pahang','Daily'),
('25200','Kuantan','Kuantan','Pahang','Daily'),
('25250','Kuantan','Kuantan','Pahang','Daily'),
('25300','Kuantan','Kuantan','Pahang','Daily'),
('25350','Kuantan','Kuantan','Pahang','Daily'),
('25500','Kuantan','Kuantan','Pahang','Daily'),
('25600','Kuantan','Kuantan','Pahang','Daily'),
('25660','Kuantan','Kuantan','Pahang','Daily'),
('25670','Kuantan','Kuantan','Pahang','Daily'),
('25690','Kuantan','Kuantan','Pahang','Daily'),
('25990','Kuantan','Kuantan','Pahang','Daily'),
('26010','Kuantan','Kuantan','Pahang','Daily'),
('26040','Kuantan','Kuantan','Pahang','Daily'),
('26050','Bukit Goh','Bukit Goh','Pahang','Daily'),
('26060','Kuantan','Kuantan','Pahang','Daily'),
('26070','Kuantan','Kuantan','Pahang','Daily'),
('26080','Kuantan','Kuantan','Pahang','Daily'),
('26090','Bukit Goh','Bukit Goh','Pahang','Daily'),
('26100','Kuantan','Kuantan','Pahang','Daily'),
('26140','Kuantan','Kuantan','Pahang','Daily'),
('26150','Balok','Balok','Pahang','Daily'),
('26180','Bukit Kuin','Bukit Kuin','Pahang','Daily'),
('26190','Balok','Balok','Pahang','Daily'),
('26200','Sungai Lembing','Sungai Lembing','Pahang','Daily'),
('26250','Kuantan','Kuantan','Pahang','Daily'),
('26309','Gambang','Gambang','Pahang','Daily'),
('26310','Gambang','Gambang','Pahang','Daily'),
('26320','Gambang','Gambang','Pahang','Daily'),
('26330','Gambang','Gambang','Pahang','Daily'),
('69000','Genting Highlands','Genting Highlands','Pahang','Saturday only'),
('69009','Genting Highlands','Genting Highlands','Pahang','Saturday only'),
-- NEGERI SEMBILAN
('70000','Seremban','Seremban','Negeri Sembilan','Daily'),
('70100','Seremban','Seremban','Negeri Sembilan','Daily'),
('70200','Seremban','Seremban','Negeri Sembilan','Daily'),
('70300','Seremban','Seremban','Negeri Sembilan','Mon, Wed, Fri'),
('70400','Seremban','Seremban','Negeri Sembilan','Daily'),
('70450','Seremban','Seremban','Negeri Sembilan','Daily'),
('70500','Seremban','Seremban','Negeri Sembilan','Daily'),
('70600','Seremban','Seremban','Negeri Sembilan','Daily'),
('70700','Seremban','Seremban','Negeri Sembilan','Daily'),
('70990','Seremban','Seremban','Negeri Sembilan','Daily'),
('71000','Port Dickson','Port Dickson','Negeri Sembilan','Mon, Wed, Fri'),
('71007','Port Dickson','Port Dickson','Negeri Sembilan','Mon, Wed, Fri'),
('71009','Port Dickson','Port Dickson','Negeri Sembilan','Mon, Wed, Fri'),
('71010','Port Dickson','Port Dickson','Negeri Sembilan','Mon, Wed, Fri'),
('71050','Si Rusa','Si Rusa','Negeri Sembilan','Mon, Wed, Fri'),
('71100','Rantau','Rantau','Negeri Sembilan','Mon, Wed, Fri'),
('71150','Linggi','Linggi','Negeri Sembilan','Daily'),
('71200','Rantau','Rantau','Negeri Sembilan','Daily'),
('71250','Si Rusa','Si Rusa','Negeri Sembilan','Mon, Wed, Fri'),
('71300','Rembau','Rembau','Negeri Sembilan','Daily'),
('71309','Rembau','Rembau','Negeri Sembilan','Daily'),
('71400','Rembau','Rembau','Negeri Sembilan','Daily'),
('71500','Tanjong Ipoh','Tanjong Ipoh','Negeri Sembilan','Daily'),
('71600','Kuala Klawang','Kuala Klawang','Negeri Sembilan','Daily'),
('71650','Kuala Klawang','Kuala Klawang','Negeri Sembilan','Daily'),
('71700','Mantin','Mantin','Negeri Sembilan','Mon, Wed, Fri'),
('71707','Mantin','Mantin','Negeri Sembilan','Mon, Wed, Fri'),
('71760','Bandar Enstek','Bandar Enstek','Negeri Sembilan','Mon, Wed, Fri'),
('71800','Nilai','Nilai','Negeri Sembilan','Mon, Wed, Fri'),
('71807','Nilai','Nilai','Negeri Sembilan','Mon, Wed, Fri'),
('71809','Nilai','Nilai','Negeri Sembilan','Mon, Wed, Fri'),
('71900','Labu','Labu','Negeri Sembilan','Mon, Wed, Fri'),
('71907','Labu','Labu','Negeri Sembilan','Mon, Wed, Fri'),
('71909','Labu','Labu','Negeri Sembilan','Mon, Wed, Fri'),
('71950','Seremban','Seremban','Negeri Sembilan','Mon, Wed, Fri'),
('71960','Port Dickson','Port Dickson','Negeri Sembilan','Mon, Wed, Fri'),
('72000','Kuala Pilah','Kuala Pilah','Negeri Sembilan','Daily'),
('72007','Kuala Pilah','Kuala Pilah','Negeri Sembilan','Daily'),
('72009','Kuala Pilah','Kuala Pilah','Negeri Sembilan','Daily'),
('72100','Bahau','Bahau','Negeri Sembilan','Daily'),
('72107','Bahau','Bahau','Negeri Sembilan','Daily'),
('72109','Bahau','Bahau','Negeri Sembilan','Daily'),
('72120','Bandar Seri Jempol','Bandar Seri Jempol','Negeri Sembilan','Daily'),
('72127','Bandar Seri Jempol','Bandar Seri Jempol','Negeri Sembilan','Daily'),
('72200','Batu Kikir','Batu Kikir','Negeri Sembilan','Daily'),
('72300','Simpang Pertang','Simpang Pertang','Negeri Sembilan','Daily'),
('72400','Simpang Durian','Simpang Durian','Negeri Sembilan','Daily'),
('72500','Kuala Pilah','Kuala Pilah','Negeri Sembilan','Daily'),
('73000','Tampin','Tampin','Negeri Sembilan','Daily'),
('73007','Tampin','Tampin','Negeri Sembilan','Daily'),
('73009','Tampin','Tampin','Negeri Sembilan','Daily'),
('73010','Tampin','Tampin','Negeri Sembilan','Daily'),
('73100','Johol','Johol','Negeri Sembilan','Daily'),
('73200','Gemencheh','Gemencheh','Negeri Sembilan','Daily'),
('73207','Gemencheh','Gemencheh','Negeri Sembilan','Daily'),
('73300','Gemencheh','Gemencheh','Negeri Sembilan','Daily'),
('73400','Gemas','Gemas','Negeri Sembilan','Daily'),
('73409','Gemas','Gemas','Negeri Sembilan','Daily'),
('73420','Gemas','Gemas','Negeri Sembilan','Daily'),
('73430','Pusat Bandar Palong','Pusat Bandar Palong','Negeri Sembilan','Tue, Thu, Sat'),
('73480','Gemas','Gemas','Negeri Sembilan','Daily'),
('73500','Rompin','Rompin','Negeri Sembilan','Daily'),
('73507','Rompin','Rompin','Negeri Sembilan','Daily'),
('73509','Rompin','Rompin','Negeri Sembilan','Daily'),
-- MELAKA
('75000','Melaka','Melaka','Melaka','Daily'),
('75050','Melaka','Melaka','Melaka','Daily'),
('75100','Melaka','Melaka','Melaka','Daily'),
('75150','Melaka','Melaka','Melaka','Daily'),
('75200','Melaka','Melaka','Melaka','Daily'),
('75250','Melaka','Melaka','Melaka','Daily'),
('75260','Melaka','Melaka','Melaka','Daily'),
('75300','Melaka','Melaka','Melaka','Daily'),
('75350','Melaka','Melaka','Melaka','Daily'),
('75400','Melaka','Melaka','Melaka','Daily'),
('75450','Ayer Keroh','Ayer Keroh','Melaka','Daily'),
('75460','Ayer Keroh','Ayer Keroh','Melaka','Daily'),
('75500','Melaka','Melaka','Melaka','Daily'),
('75550','Melaka','Melaka','Melaka','Daily'),
('75600','Melaka','Melaka','Melaka','Daily'),
('75700','Melaka','Melaka','Melaka','Daily'),
('75710','Melaka','Melaka','Melaka','Daily'),
('75720','Melaka','Melaka','Melaka','Daily'),
('75730','Melaka','Melaka','Melaka','Daily'),
('75750','Melaka','Melaka','Melaka','Daily'),
('75760','Melaka','Melaka','Melaka','Daily'),
('75900','Melaka','Melaka','Melaka','Daily'),
('75990','Melaka','Melaka','Melaka','Daily'),
('76100','Durian Tunggal','Durian Tunggal','Melaka','Daily'),
('76109','Durian Tunggal','Durian Tunggal','Melaka','Daily'),
('76200','Kem Trendak','Kem Trendak','Melaka','Daily'),
('76300','Sungai Udang','Sungai Udang','Melaka','Daily'),
('76400','Tanjong Kling','Tanjong Kling','Melaka','Daily'),
('76450','Melaka','Melaka','Melaka','Daily'),
('77000','Jasin','Jasin','Melaka','Daily'),
('77007','Jasin','Jasin','Melaka','Daily'),
('77008','Jasin','Jasin','Melaka','Daily'),
('77009','Jasin','Jasin','Melaka','Daily'),
('77100','Asahan','Asahan','Melaka','Daily'),
('77109','Asahan','Asahan','Melaka','Daily'),
('77200','Bemban','Bemban','Melaka','Daily'),
('77300','Merlimau','Merlimau','Melaka','Daily'),
('77307','Merlimau','Merlimau','Melaka','Daily'),
('77309','Merlimau','Merlimau','Melaka','Daily'),
('77400','Sungai Rambai','Sungai Rambai','Melaka','Daily'),
('77500','Selandar','Selandar','Melaka','Daily'),
('77507','Selandar','Selandar','Melaka','Daily'),
('77509','Selandar','Selandar','Melaka','Daily'),
('78000','Alor Gajah','Alor Gajah','Melaka','Daily'),
('78007','Alor Gajah','Alor Gajah','Melaka','Daily'),
('78009','Alor Gajah','Alor Gajah','Melaka','Daily'),
('78100','Lubok China','Lubok China','Melaka','Daily'),
('78200','Kuala Sungai Baru','Kuala Sungai Baru','Melaka','Daily'),
('78300','Masjid Tanah','Masjid Tanah','Melaka','Daily'),
('78307','Masjid Tanah','Masjid Tanah','Melaka','Daily'),
('78309','Masjid Tanah','Masjid Tanah','Melaka','Daily'),
-- JOHOR
('79000','Iskandar Puteri','Iskandar Puteri','Johor','Daily'),
('79050','Iskandar Puteri','Iskandar Puteri','Johor','Daily'),
('79100','Iskandar Puteri','Iskandar Puteri','Johor','Daily'),
('79150','Iskandar Puteri','Iskandar Puteri','Johor','Daily'),
('79200','Iskandar Puteri','Iskandar Puteri','Johor','Daily'),
('79250','Iskandar Puteri','Iskandar Puteri','Johor','Daily'),
('79502','Iskandar Puteri','Iskandar Puteri','Johor','Daily'),
('79550','Iskandar Puteri','Iskandar Puteri','Johor','Daily'),
('79660','Iskandar Puteri','Iskandar Puteri','Johor','Daily'),
('79680','Iskandar Puteri','Iskandar Puteri','Johor','Daily'),
('80000','Johor Bahru','Johor Bahru','Johor','Daily'),
('80050','Johor Bahru','Johor Bahru','Johor','Daily'),
('80100','Johor Bahru','Johor Bahru','Johor','Daily'),
('80150','Johor Bahru','Johor Bahru','Johor','Daily'),
('80200','Johor Bahru','Johor Bahru','Johor','Daily'),
('80250','Johor Bahru','Johor Bahru','Johor','Daily'),
('80300','Johor Bahru','Johor Bahru','Johor','Daily'),
('80350','Johor Bahru','Johor Bahru','Johor','Daily'),
('80400','Johor Bahru','Johor Bahru','Johor','Daily'),
('80500','Johor Bahru','Johor Bahru','Johor','Daily'),
('80600','Johor Bahru','Johor Bahru','Johor','Daily'),
('80700','Johor Bahru','Johor Bahru','Johor','Daily'),
('80900','Johor Bahru','Johor Bahru','Johor','Daily'),
('80990','Johor Bahru','Johor Bahru','Johor','Daily'),
('81000','Kulai','Kulai','Johor','Daily'),
('81007','Kulai','Kulai','Johor','Daily'),
('81009','Kulai','Kulai','Johor','Daily'),
('81010','Kulai','Kulai','Johor','Daily'),
('81020','Kulai','Kulai','Johor','Daily'),
('81030','Kulai','Kulai','Johor','Daily'),
('81040','Kulai','Kulai','Johor','Daily'),
('81100','Johor Bahru','Johor Bahru','Johor','Daily'),
('81107','Johor Bahru','Johor Bahru','Johor','Daily'),
('81110','Gelang Patah','Johor Bahru','Johor','Daily'),
('81120','Gelang Patah','Johor Bahru','Johor','Daily'),
('81150','Pekan Nenas','Pontian','Johor','Daily'),
('81200','Johor Bahru','Johor Bahru','Johor','Daily'),
('81300','Skudai','Johor Bahru','Johor','Daily'),
('81307','Johor Bahru','Johor Bahru','Johor','Daily'),
('81310','Johor Bahru','Johor Bahru','Johor','Daily'),
('81400','Senai','Kulai','Johor','Daily'),
('81407','Senai','Kulai','Johor','Daily'),
('81500','Pekan Nenas','Pontian','Johor','Daily'),
('81507','Pekan Nenas','Pontian','Johor','Daily'),
('81550','Gelang Patah','Johor Bahru','Johor','Daily'),
('81560','Gelang Patah','Johor Bahru','Johor','Daily'),
('81600','Pengerang','Kota Tinggi','Johor','Mon, Wed, Fri'),
('81620','Pengerang','Kota Tinggi','Johor','Mon, Wed, Fri'),
('81700','Pasir Gudang','Pasir Gudang','Johor','Mon, Wed, Fri'),
('81707','Pasir Gudang','Pasir Gudang','Johor','Mon, Wed, Fri'),
('81750','Masai','Johor Bahru','Johor','Mon, Wed, Fri'),
('81757','Masai','Johor Bahru','Johor','Mon, Wed, Fri'),
('81760','Masai','Johor Bahru','Johor','Mon, Wed, Fri'),
('81800','Ulu Tiram','Johor Bahru','Johor','Daily'),
('81807','Ulu Tiram','Johor Bahru','Johor','Daily'),
('81809','Ulu Tiram','Johor Bahru','Johor','Daily'),
('81810','Ulu Tiram','Johor Bahru','Johor','Daily'),
('81850','Layang-Layang','Kluang','Johor','Daily'),
('81900','Kota Tinggi','Kota Tinggi','Johor','Mon, Wed, Fri'),
('81907','Kota Tinggi','Kota Tinggi','Johor','Mon, Wed, Fri'),
('81910','Kota Tinggi','Kota Tinggi','Johor','Mon, Wed, Fri'),
('81920','Ayer Tawar 2','Kota Tinggi','Johor','Mon, Wed, Fri'),
('81930','Bandar Penawar','Kota Tinggi','Johor','Mon, Wed, Fri'),
('81960','Kota Tinggi','Kota Tinggi','Johor','Mon, Wed, Fri'),
('82000','Pontian','Pontian','Johor','Daily'),
('82007','Pontian','Pontian','Johor','Daily'),
('82009','Pontian','Pontian','Johor','Daily'),
('82010','Pontian','Pontian','Johor','Daily'),
('82020','Pontian','Pontian','Johor','Daily'),
('82030','Kukup','Pontian','Johor','Daily'),
('82100','Ayer Baloi','Pontian','Johor','Daily'),
('82200','Benut','Pontian','Johor','Daily'),
('82207','Benut','Pontian','Johor','Daily'),
('82300','Kukup','Pontian','Johor','Daily'),
('83000','Batu Pahat','Batu Pahat','Johor','Daily'),
('83007','Batu Pahat','Batu Pahat','Johor','Daily'),
('83009','Batu Pahat','Batu Pahat','Johor','Daily'),
('83010','Batu Pahat','Batu Pahat','Johor','Daily'),
('83100','Rengit','Batu Pahat','Johor','Daily'),
('83200','Senggarang','Batu Pahat','Johor','Daily'),
('83300','Seri Gading','Batu Pahat','Johor','Daily'),
('83400','Sri Medan','Batu Pahat','Johor','Daily'),
('83500','Parit Sulong','Batu Pahat','Johor','Daily'),
('83600','Semerah','Batu Pahat','Johor','Daily'),
('83700','Yong Peng','Batu Pahat','Johor','Daily'),
('84000','Muar','Muar','Johor','Daily'),
('84007','Muar','Muar','Johor','Daily'),
('84010','Muar','Muar','Johor','Daily'),
('84020','Tangkak','Muar','Johor','Daily'),
('84030','Pagoh','Muar','Johor','Daily'),
('84040','Pagoh','Muar','Johor','Daily'),
('84050','Muar','Muar','Johor','Daily'),
('84100','Parit Jawa','Muar','Johor','Daily'),
('84200','Muar','Muar','Johor','Daily'),
('84300','Bukit Pasir','Muar','Johor','Daily'),
('84400','Sungai Mati','Muar','Johor','Daily'),
('84407','Sungai Mati','Muar','Johor','Daily'),
('84500','Panchor','Muar','Johor','Daily'),
('84600','Pagoh','Muar','Johor','Daily'),
('84700','Gerisek','Muar','Johor','Daily'),
('84710','Gerisek','Muar','Johor','Daily'),
('84800','Bukit Gambir','Muar','Johor','Daily'),
('84900','Tangkak','Tangkak','Johor','Daily'),
('84907','Tangkak','Tangkak','Johor','Daily'),
('85000','Segamat','Segamat','Johor','Tue, Thu, Sat'),
('85007','Segamat','Segamat','Johor','Tue, Thu, Sat'),
('85009','Segamat','Segamat','Johor','Tue, Thu, Sat'),
('85010','Segamat','Segamat','Johor','Tue, Thu, Sat'),
('85020','Segamat','Segamat','Johor','Tue, Thu, Sat'),
('85100','Batu Anam','Segamat','Johor','Tue, Thu, Sat'),
('85109','Batu Anam','Segamat','Johor','Tue, Thu, Sat'),
('85200','Jementah','Segamat','Johor','Tue, Thu, Sat'),
('85300','Labis','Segamat','Johor','Tue, Thu, Sat'),
('85307','Labis','Segamat','Johor','Tue, Thu, Sat'),
('85309','Labis','Segamat','Johor','Tue, Thu, Sat'),
('85400','Chaah','Segamat','Johor','Tue, Thu, Sat'),
('86000','Kluang','Kluang','Johor','Daily'),
('86007','Kluang','Kluang','Johor','Daily'),
('86009','Kluang','Kluang','Johor','Daily'),
('86100','Ayer Hitam','Kluang','Johor','Daily'),
('86107','Ayer Hitam','Kluang','Johor','Daily'),
('86200','Simpang Rengam','Kluang','Johor','Daily'),
('86207','Simpang Rengam','Kluang','Johor','Daily'),
('86300','Rengam','Kluang','Johor','Daily'),
('86400','Parit Raja','Batu Pahat','Johor','Daily'),
('86407','Parit Raja','Batu Pahat','Johor','Daily'),
('86500','Bekok','Segamat','Johor','Tue, Thu, Sat'),
('86600','Paloh','Kluang','Johor','Daily'),
('86700','Kahang','Kluang','Johor','Mon, Wed, Fri'),
('86707','Kahang','Kluang','Johor','Mon, Wed, Fri'),
('86800','Mersing','Mersing','Johor','Mon, Wed, Fri'),
('86807','Mersing','Mersing','Johor','Mon, Wed, Fri'),
('86810','Mersing','Mersing','Johor','Mon, Wed, Fri'),
('86900','Endau','Mersing','Johor','Mon, Wed, Fri')
on conflict (postcode) do nothing;
