-- ============================================================
-- 039_fix_stock.sql
-- Set stock awal untuk semua produk yang zero stock
--
-- Sistem inventory:
--   - Produk DENGAN variants → product_variants.stock
--   - Produk TANPA variants  → inventory_batches (dikira oleh product_stock view)
--
-- Stock default = 50 unit (tukar mengikut stok sebenar selepas run)
-- ============================================================

-- ── 1. Variant products: set stock = 50 untuk semua zero stock ────────────────
update public.product_variants
set stock = 50
where stock = 0
  and is_active = true;

-- ── 2. Non-variant products: insert inventory batch jika tiada ───────────────
-- (Produk yang tiada dalam product_variants langsung)
insert into public.inventory_batches (product_id, quantity, batch_date, expiry_date, supplier, notes)
select
  p.id,
  50,                                          -- stok awal
  current_date,                                -- tarikh batch hari ini
  current_date + interval '1 year',            -- tempoh luput 1 tahun
  'Stok Awal',
  'Auto-generated by migration 039'
from public.products p
where p.is_active = true
  and not exists (
    select 1 from public.product_variants pv
    where pv.product_id = p.id
      and pv.is_active = true
  )
  and not exists (
    select 1 from public.inventory_batches ib
    where ib.product_id = p.id
      and ib.quantity > 0
  );

-- ── Verify ───────────────────────────────────────────────────────────────────
-- Jalankan query ini untuk semak hasil:
--
-- SELECT 'variant_zero_stock' as check, count(*) FROM product_variants WHERE stock = 0 AND is_active = true
-- UNION ALL
-- SELECT 'variant_with_stock', count(*) FROM product_variants WHERE stock > 0 AND is_active = true
-- UNION ALL
-- SELECT 'non_variant_batches', count(*) FROM inventory_batches WHERE notes LIKE '%migration 039%';
